# Code Generated by ZenTest v. 3.11.0
#                 classname: asrt / meth =  ratio%
#                       Dog:    0 /    8 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'lib/dog'
class TestDog < Test::Unit::TestCase
  def test_class_snore
    assert_equal("<<fall asleep snoring like a mad>>",Dog.snore)
  end

  def test_bark
    dog = Dog.new('dog')
    assert_equal("<<warf! warf!>>",dog.bark)
  end

  def test_chase_cat
    dog = Dog.new('dog')
    assert_equal("<<grrr!!!>>", dog.chase_cat)
    dog = Dog.new('dog',true)
    assert_equal("<<crossed her paws on her eyes as a sign of dissaproval>>", dog.chase_cat)
  end

  def test_eat
    dog = Dog.new('dog')
    assert_equal("<<slurp!!!>>",dog.eat)
  end

  def test_name_equals
    dog = Dog.new('dog')
    dog.name = 'dog1'
    assert_equal('dog1', dog.name)
    dog = Dog.new('dog1', true)
    dog.name = 'dog'
    assert_equal('dog', dog.name)
  end

  def test_pacifist
    dog = Dog.new('dog')
    assert_equal(false, dog.pacifist)
    dog = Dog.new('dog', true)
    assert_equal(true, dog.pacifist)
  end

  def test_pacifist_equals
    dog = Dog.new('dog')
    dog.pacifist = true
    assert_equal(true, dog.pacifist)
    dog = Dog.new('dog', true)
    dog.pacifist = false
    assert_equal(false, dog.pacifist)
  end

  def test_wants_to_wag
    dog = Dog.new('dog')
    assert_equal(nil, dog.wants_to_wag)
    dog = Dog.new('Zita')
    assert_equal("<<with a wage of her tail>>", dog.wants_to_wag)
  end
end

# Number of errors detected: 9
